//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCliente_TblProducto
    {
        public int cantidad { get; set; }
        public string codBarra { get; set; }
        public string cedula { get; set; }
    
        public virtual TblProducto TblProducto { get; set; }
        public virtual TblClientes TblClientes { get; set; }
    }
}
