//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProducto()
        {
            this.TblCliente_TblProducto = new HashSet<TblCliente_TblProducto>();
        }
    
        public string codBarra { get; set; }
        public string cedulaLegal { get; set; }
        public string unidadMedida { get; set; }
        public string foto { get; set; }
        public string estado { get; set; }
        public decimal precioVenta { get; set; }
        public int idClasificacion { get; set; }
        public string nombreProducto { get; set; }
        public string descripcion { get; set; }
        public string exento { get; set; }
        public Nullable<decimal> precioCompra { get; set; }
        public Nullable<decimal> impuestoIVA { get; set; }
        public Nullable<decimal> impuestoVenta { get; set; }
        public Nullable<decimal> totalImpuestos { get; set; }
    
        public virtual TblClasificacion TblClasificacion { get; set; }
        public virtual TblProveedor TblProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCliente_TblProducto> TblCliente_TblProducto { get; set; }
    }
}
