//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProducto()
        {
            this.TblProveedor_TblProducto = new HashSet<TblProveedor_TblProducto>();
            this.TblCliente_TblProducto = new HashSet<TblCliente_TblProducto>();
        }
    
        public string codBarra { get; set; }
        public decimal descuento { get; set; }
        public string unidadMedida { get; set; }
        public string foto { get; set; }
        public string estado { get; set; }
        public int idClasificacion { get; set; }
    
        public virtual TblClasificacion TblClasificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProveedor_TblProducto> TblProveedor_TblProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCliente_TblProducto> TblCliente_TblProducto { get; set; }
    }
}
