//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProveedor_TblProducto
    {
        public decimal precioVenta { get; set; }
        public string codBarra { get; set; }
        public string cedulaLegal { get; set; }
    
        public virtual TblProducto TblProducto { get; set; }
        public virtual TblProveedor TblProveedor { get; set; }
    }
}
